### ISSUE TITLE
GH Action taking doubled the time

### ISSUE THREAD

**Issue by ToldoDM** [dante-ev/docker-texlive#20]
I have an action based on this image, and 4 days ago my action started taking double the time. From 3:30 minutes to 7-8 minutes.
Is there a way i can use a previous version of the docker image? 

Actually the action that i'm using is this one: https://github.com/Jatus93/Latex-multicompiler on release 1.
The dockerfile of this action look like this
```
FROM danteev/texlive

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
```

**Comment by koppor** [comment]
Does the initialization of the action take longer or the acutal compile? For the former, I hope that caching will solve it. I am currently experimenting with the "official" texlive Docker image (https://gitlab.com/islandoftex/images/texlive#tex-live-docker-image), because thereby it is ensured that always the latest texlive is used.

I suppose the action https://github.com/dante-ev/latex-action was too outdated for you?

**Comment by ToldoDM** [comment]
I'm actually new to docker and GH Actions.
Anyway, i can ensure you that the section on compiling is the same as before (less than 30 seconds). The most time consuming task is when the action download the image, so as you said `I hope that caching will solve it`: how can i cache the image?

`I suppose the action https://github.com/dante-ev/latex-action was too outdated for you?`
I've tried that action, but the one i'm using is more suitable for my type of job and is easy to use (cause as i said before, i'm new to this kind of things).

**Comment by koppor** [comment]
I think, this is https://github.com/dante-ev/latex-action/issues/7. Thus I close this issue to focus the discussion.

**Comment by ToldoDM** [comment]
thank you for your help, i'll follow that issue, also because i'm changing my workflow on that action. 
I think this issue can be closed.
